# Generated by Django 3.0.5 on 2020-04-21 13:47

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(blank=True, max_length=100, null=True)),
                ('accredited', models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('special_general', models.CharField(blank=True, choices=[('ad', 'ADMINISTRATION'), ('sg', 'AGRICULTURE'), ('ar', 'ARCHITECTURE'), ('br', 'BROADCASTING OR MEDIA'), ('co', 'COMMUNICATIONS'), ('cm', 'COMMUNITY DEVELOPMENT'), ('de', 'DEFENSE'), ('di', 'DISASTER MANAGEMENT'), ('ec', 'ECONOMICS'), ('eu', 'EDUCATION AND TRAINING AND PUBLIC AWARENESS'), ('el', 'ELECTIRCIAN'), ('fi', 'FINANCE'), ('fr', 'FIRE AND SEARCH AND RESCUE'), ('fi', 'FIRST AID INSTRUCTOR'), ('fo', 'FOREIGN AFFAIRS'), ('he', 'HEALTH EDUCATION'), ('la', 'LAND VALUATION'), ('ma', 'MANAGEMENT'), ('mr', 'MARITIME'), ('me', 'MEDICAL METEREOLOGICAL_SERVICES'), ('mi', 'MINERAL RESOURCES'), ('na', 'NATIONAL PLANNING'), ('po', 'POLICE'), ('', 'PRISON SERVICES'), ('pu', 'PUBLIC HEALTH'), ('pb', 'PUBLIC WORK AND WATER'), ('re', 'RED CROSS'), ('rs', 'RESEARCH DEPARTMENT'), ('tr', 'TRANSPORT')], max_length=200, null=True)),
                ('special_disaster_management', models.CharField(blank=True, choices=[('co', 'COORDINATION'), ('da', 'DAMAGE ASSEMENT AND PLANNING'), ('', 'DISASTER OPERATION'), ('ed', 'EDUCATION AND TRAINING'), ('ha', 'HAZARD ASSEMENT'), ('mi', 'MITIGATION AND PREVENTION'), ('ne', 'NEEDS ANALYSIS AND IMPLEMENTATION'), ('pr', 'PREPAREDNESS PLANNING')], max_length=100, null=True)),
                ('sector', models.CharField(blank=True, choices=[('CS', 'Civil Service'), ('IO', 'International Organization'), ('NG', 'National Government'), ('PS', 'Private Sector'), ('RO', 'Regional Organization'), ('O', 'Others')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('trainer', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Hon', 'Hon')], max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('position', models.CharField(max_length=1000)),
                ('contact_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=100, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('pr', 'Primary'), ('se', 'Secondary'), ('te', 'Tertiary'), ('vo', 'Vocational')], max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('organization', models.ManyToManyField(related_name='host_organization', to='app.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('ojective', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_activity', models.CharField(max_length=100)),
                ('documents', models.FileField(blank=True, null=True, upload_to='')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('day_number', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('attendees_number', models.IntegerField(blank=True, default=1, null=True)),
                ('method', models.CharField(blank=True, choices=[('tc', 'TrainingCL'), ('t', 'Training'), ('w', 'Workshop')], max_length=50, null=True)),
                ('period', models.CharField(blank=True, choices=[('Hours', 'Hours'), ('Days', 'Days'), ('Weeks', 'Weeks'), ('months', 'Months')], max_length=50, null=True)),
                ('session_type', models.CharField(blank=True, choices=[('in', 'in_country technical assistance'), ('ic', 'international course'), ('na', 'national course'), ('ns', 'national seminar or workshop'), ('po', 'post grad certificate programs'), ('rc', 'regional course'), ('re', 'regional seminar or workshop'), ('su', 'sub national course'), ('c', 'Consultation')], max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course')),
                ('course_unit_names', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Unit')),
                ('participant', models.ManyToManyField(related_name='host_participant', to='app.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('donor', models.CharField(blank=True, max_length=100, null=True)),
                ('odjective', models.CharField(blank=True, max_length=1000, null=True)),
                ('work_plan', models.CharField(blank=True, max_length=1000, null=True)),
                ('key_result_area', models.CharField(blank=True, max_length=1000, null=True)),
                ('output', models.CharField(blank=True, max_length=1000, null=True)),
                ('evaluation', models.CharField(blank=True, max_length=1000, null=True)),
                ('funding', models.CharField(blank=True, max_length=1000, null=True)),
                ('head_of_project', models.CharField(blank=True, max_length=1000, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('target_audience', models.CharField(blank=True, max_length=1000, null=True)),
                ('overview_about_project', models.CharField(blank=True, max_length=1000, null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Program')),
            ],
        ),
        migrations.CreateModel(
            name='ListOfParticpantsWhoCompletedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course')),
                ('participant_list', models.ManyToManyField(related_name='courseparticipant', to='app.Participant')),
                ('sessions', models.ManyToManyField(related_name='host_session', to='app.Session')),
                ('unit_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Program'),
        ),
        migrations.AddField(
            model_name='course',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
    ]
