# Generated by Django 3.0.5 on 2020-07-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200720_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='special_disaster_management',
            field=models.CharField(blank=True, choices=[('co', 'COORDINATION'), ('da', 'DAMAGE ASSEMENT AND PLANNING'), ('', 'DISASTER OPERATION'), ('ed', 'EDUCATION AND TRAINING'), ('ha', 'HAZARD ASSESSMENT'), ('mi', 'MITIGATION AND PREVENTION'), ('ne', 'NEEDS ANALYSIS AND IMPLEMENTATION'), ('pr', 'PREPAREDNESS PLANNING')], max_length=100, null=True),
        ),
    ]
