# Generated by Django 3.0.5 on 2020-07-20 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200720_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='odjective',
            new_name='objective',
        ),
    ]
