# Generated by Django 3.0.8 on 2020-07-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_session_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='course_units',
            field=models.ManyToManyField(related_name='course_units', to='app.Unit'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(blank=True, choices=[('In-Country', 'In-Country'), ('Regional', 'Regional')], max_length=50, null=True),
        ),
    ]
