# Generated by Django 3.0.8 on 2020-08-05 22:12

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200727_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('position', models.CharField(max_length=1000)),
                ('comments', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('fax_number', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.ManyToManyField(related_name='trainer_host_organization', to='app.Organization')),
            ],
        ),
    ]
