# Generated by Django 3.0.8 on 2020-08-11 00:18

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_session_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assesors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Hon', 'Hon')], max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('position', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_units',
            field=models.ManyToManyField(blank=True, related_name='course_assessors', to='app.Assesors'),
        ),
    ]
