# Generated by Django 3.0.8 on 2020-08-11 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200811_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_units',
            new_name='assessor',
        ),
    ]
