# Generated by Django 3.0.8 on 2020-08-11 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200811_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assesors',
            options={'verbose_name': 'Assesor', 'verbose_name_plural': 'Assesors'},
        ),
    ]
